name: FeOH
version: $(plugin_version)
author: UnstableProgrammers
api-version: 1.16
main: de.unstableprogrammers.feoh.main.FeOH
commands:
  givematerialspawner:
  givetools:
  givematerials:
  giveworkstations:
  givecomponents:
  console: