name: Rust
version: $(plugin_version)
author: UnstableProgrammers
api-version: 1.16
main: de.unstableprogrammers.rust.main.Rust
commands:
  givematerialspawner:
  givetools:
  givematerials:
  giveworkstations:
  givecomponents:
  console: